backend:
  name: git-gateway                 
  repo: yotmanreyes/conexstudios-docs
  branch: main
auth_scope: repo
publish_mode: editorial_workflow
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string", default: "Nombre del autor"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
      
  - name: "docs"
    label: "Documentación"
    folder: "docs"
    create: true
    fields:
      - {label: "ID de la barra lateral", name: "id", widget: "string", hint: "Debe ser único. Usado para el slug de la URL"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Sidebar Position", name: "sidebar_position", widget: "number", default: 1}
      - {label: "Cuerpo", name: "body", widget: "markdown"}